### ISSUE TITLE
Importing from local files doesn't get colored properly

### ISSUE THREAD

**Issue by joshichaitanya3** [mattsep/morpho-vscode#1]
Morpho allows uses to import their own modules locally via
`import "module.morpho"`

The syntax highlighter currently doesn't recognize this as an import, and so we get something like this:
![image](https://user-images.githubusercontent.com/16670570/153540804-ae9feb5c-126d-4c40-81c8-fc4fb225584c.png)

**Comment by mattsep** [comment]
Oh yep, I forgot that paths to modules as strings are allowed to be import targets
