### ISSUE TITLE
Some of the valid symbols don't get colored properly

### ISSUE THREAD

**Issue by joshichaitanya3** [mattsep/morpho-vscode#2]
The syntax highlighter doesn't color some of the [valid symbols](https://github.com/Morpho-lang/morpho/blob/main/morpho5/docs/syntax.md#symbols) properly. Looks like it has something to do with the underscore:
![image](https://user-images.githubusercontent.com/16670570/153541403-8e41b513-f8f9-4b31-84bc-c355e692dcbc.png)

**Comment by mattsep** [comment]
Oops, that's quite an oversight. Looks like I forgot to allow underscores in identifiers after the first character...
